# This is a basic workflow to help you get started with Actions

name: Crawl ZHIHU

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    #     - cron: '24 0,6,12 * * *'
    - cron: "24 23 * * *"

# Env variables
env:
  NewsURL: ${{ secrets.NewsURL }}
  BOTTOKEN: ${{ secrets.BOTTOKEN }}
  CHATID: ${{ secrets.CHATID }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Install jq
        run: sudo apt-get install jq
      - name: test push
        run: |
          curl $NewsURL | jq ".data[0].content" > 123.txt
          myee=$(curl "http://dict.youdao.com/infoline?mode=publish&apiversion=5.0&date=$(date +%s)" | jq 'first(.[])' | jq ".[0].title, .[0].summary")
          echo "<myee>"$myee"</myee>" >> 123.txt
          imageUrl=$(curl "https://api.j4u.ink/v1/store/other/proxy/remote/moyu.json" | jq ".data.moyu_url")
          imageUrl=${imageUrl%\"}
          imageUrl=${imageUrl#\"}
          curl ${imageUrl} -o 123.png -L
          git config --global user.name "123@gmail"
          git config --global user.email "123@gmail.com"
          git add -A
          git commit -m "Update 123.txt"
          git push
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot
          pip install requests
      - name: test news
        run: |
          python main.py
