# This is a basic workflow to help you get started with Actions

name: Crawl ZHIHU

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    #     - cron: '24 0,6,12 * * *'
    - cron: "24 23 * * *"

# Env variables
env:
  MHK: ${{ secrets.MHK }}
  NEWSURL: ${{ secrets.NEWSURL }}
  BOTTOKEN: ${{ secrets.BOTTOKEN }}
  CHATID: ${{ secrets.CHATID }}
  CHATID2: ${{ secrets.CHATID2 }}
  CHATID3: ${{ secrets.CHATID3 }}
  YDDICT: ${{ secrets.YDDICT }}
  MOYU: ${{ secrets.MOYU }}
  ENGLISHURL: ${{ secrets.ENGLISHURL }}
  ICIBAURL: ${{ secrets.ICIBAURL }}
  DEVELOPURL: ${{ secrets.DEVELOPURL }}
  XIAOAIURL1: ${{ secrets.XIAOAIURL1 }}
  XIAOAIURL2: ${{ secrets.XIAOAIURL2 }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
      - name: Install jq
        run: sudo apt-get install jq
      - name: Get news and Commit
        run: |
          imageUrl=$(curl $MOYU | jq ".data.moyu_url")
          echo $imageUrl
